config/routes.rb
BgDryRunApp::Application.routes.draw do
  
  resources :matches do
    resources :players
    resources :base_modules
    resources :videos
  end

  root to: 'matches#index'
  get "matches/:match_id/videos/new/location", to: "locations#new", as: "direct_upload_form"

end

app/models/base_module.rb
class BaseModule < ActiveRecord::Base
  belongs_to :match
  has_many :clips
  
  attr_accessible :name, :report, :match_id, :report_run

  validates :name, :report, :match_id, presence: true

  mount_uploader :report, ReportUploader

  def tags
    split_tags = self.split_tags
    rejoined_tags = []
    split_tags.each do |split_tag|
      rejoined_tags << split_tag.join(" ")
    end
    rejoined_tags
  end

  def split_tags
    tags_array = self.tags_array
    tags_array.map { |tag| tag.split "," }
  end

  def tags_array
    file = self.get_report
    file.split "\n"
  end

  def get_report
    open(self.report.url).read
  end

  scope :unrun, where(report_run: false)
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  attr_accessible :match_id, :url, :player_id, :transcoded, :base_module_id, :tag_time, :video_id
  
  belongs_to :match
  belongs_to :player
  belongs_to :base_module
  belongs_to :video

  default_scope where(transcoded: true)

  def self.unavailable
    unscoped.where(transcoded: false)
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :name, :play_date, :videos_attributes, :players_attributes


  has_many :clips, dependent: :destroy
  has_many :videos, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :base_modules, dependent: :destroy

  accepts_nested_attributes_for :videos
  accepts_nested_attributes_for :players

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :match

  has_many :clips
  attr_accessible :first_name, :last_name, :upi, :match_id

  validates :upi, :first_name, :last_name, presence: true

  def name
    self.first_name + " " + self.last_name    
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :match
  has_many :clips
  attr_accessible :audio_channels, :audio_sample_rate, :audio_stream, :bitrate, :container, :creation_time, :duration, :height, :location, :video_codec, :video_stream, :width, :camera, :match_id

  mount_uploader :location, MatchVideoUploader

  validates :match_id, presence: true

  def duration_in_minutes
    (self.duration / 60).round(2)
  end

  def set_ffmpeg_path_to_video
    url = self.location.url
    open(url).path
  end

  def get_ffmpeg_data
    path_to_video = self.set_ffmpeg_path_to_video
    FFMPEG::Movie.new path_to_video
  end

  def add_metadata_to_video
    ffmpeg_data = self.get_ffmpeg_data
    self.audio_channels = ffmpeg_data.audio_channels
    self.audio_sample_rate = ffmpeg_data.audio_sample_rate
    self.audio_stream = ffmpeg_data.audio_stream
    self.bitrate = ffmpeg_data.bitrate
    self.container = ffmpeg_data.container
    self.creation_time = ffmpeg_data.creation_time
    self.duration = ffmpeg_data.duration
    self.width = ffmpeg_data.width if ffmpeg_data.width > 0
    self.height = ffmpeg_data.height if ffmpeg_data.height > 0
    self.video_codec = ffmpeg_data.video_codec
    self.video_stream = ffmpeg_data.video_stream
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/base_modules_controller.rb
class BaseModulesController < ApplicationController
  def new
    @match = Match.find params[:match_id]
    @base_module = BaseModule.new
  end

  def create
    @base_module = BaseModule.new params[:base_module]

    if @base_module.save
      redirect_to @base_module.match, notice: "Report added!"
    else
      render :new
    end
  end

  def show
    @base_module = BaseModule.find params[:id]
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @uploader = Video.new.location
    @uploader.success_action_redirect = new_match_video_url
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = Match.all
  end

  def new
    @match = Match.new

    10.times { @match.players.build }
  end

  def create
    if players_attributes = params[:match][:players_attributes]
      players_attributes.delete_if do |key,value|
        players_attributes[key]["upi"].blank?
      end
      params[:match][:players_attributes] = players_attributes
    end

    @match = Match.new params[:match]
    
    if @match.save
      redirect_to matches_path, notice: "Match #{@match.name} saved."
    else
      more_players_count = 10 - @match.players.count
      more_players_count.times { @match.players.build }
      render 'new'
    end
  end

  def show
    @match = Match.find params[:id]
  end

  def edit
  end

  def destroy
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def new
    match_id = params[:match_id]
    @match = Match.find match_id
    @video = Video.new match_id: match_id, key: params[:key]
  end

  def create
    @video = Video.new params[:video]

    if @video.save
      set_ffmpeg_binary
      @video.add_metadata_to_video
      redirect_to @video.match, notice: "Video added!"
    else
      render :new
    end
  end

  def set_ffmpeg_binary
    StreamioHelper.set_ffmpeg_binary
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_modules_helper.rb
module BaseModulesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/base_modules/new.html.haml
%h1 BaseModules#new

= form_for [@match, @base_module] do |f|
  = f.label :name
  = f.text_field :name, size: 5, required: true
  = f.hidden_field :match_id, value: @match.id
  %br
  = f.label :report
  = f.file_field :report, required: true
  %br
  = f.submit

app/views/base_modules/show.html.haml
%h1
  = "Base Module #{@base_module.name}"
%ol
  - @base_module.tags.each do |tag|
    %li
      = tag

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = yield(:title).empty? ? 'BG' : yield(:title)
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}
  %body
    .notices
      = notice
    = yield
    .push

app/views/locations/new.html.haml
%h1 Videos#new

= direct_upload_form_for @uploader do |f|
  = f.file_field :location
  = f.submit "Upload Video"

app/views/matches/_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    .errors
      = @match.errors.full_messages.join(', ').downcase.capitalize
  = f.label :name, "Match Name"
  = f.text_field :name, required: true
  %br
  %br
  = label_tag "Add Players (up to 10, can add more later)"
  %br
  %br
  UPI is Unique Player Identifier (e.g., "A1")
  %br
  %br
  = f.fields_for :players do |p|
    .add-player-fields.hidden-add-player
      = p.label :upi, "UPI"
      = p.text_field :upi
      = p.label :first_name
      = p.text_field :first_name
      = p.label :last_name
      = p.text_field :last_name
      %br
  %br
  %button#add-player-button
    Add Player
  = f.submit

app/views/matches/edit.html.haml
%h1 Matches#edit
%p Find me in app/views/matches/edit.html.haml

app/views/matches/index.html.haml
%h1 Matches#index
%br
= link_to "Add Match", new_match_path
%br
%br
- @matches.each do |match|
  = link_to match.name, match
  

app/views/matches/new.html.haml
%h1 Matches#new
= render "form"

app/views/matches/show.html.haml
%h1
  = @match.name
%br
%h2 Additions
= link_to "Add Video", direct_upload_form_path(@match)
= link_to "Add Base Module Report", new_match_base_module_path(@match)
= link_to "Add Player", new_match_player_path(@match)
%h2 Videos
%ul
  - @match.videos.each do |video|
    %li
      %ul
        %li
          = video.camera
        %li
          = video.creation_time
        %li
          = pluralize video.duration_in_minutes, "minute"
        %li
          = video_tag video.location.url, controls: true
%h2 Base Modules
%ul
  - @match.base_modules.each do |bm|
    %li
      = link_to bm.name, match_base_module_path(@match, bm)
%h2 Players
- @match.players.each do |player|
  %h3
    = "#{player.upi}: #{player.name}"
  %h4 Clips
  %br
  - player.clips.each do |clip|
    %div
      = video_tag clip.url, controls: true
    %br
  %br
  %br

app/views/players/new.html.haml
%h1 Players#new
%p Find me in app/views/players/new.html.haml

app/views/videos/new.html.haml
%h1 Videos#new
%h3 Which camera?

= form_for [@match, @video] do |f|
  = f.label :camera
  = f.text_field :camera
  = f.hidden_field :match_id
  = f.hidden_field :key
  %br
  = f.submit